services:
  - type: web
    name: oxv-bot
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000
